---
- name: Install prefered packages
  ansible.builtin.apt:
    pkg:
      - htop
      - iotop
      - strace

# - name: Install required packages
#   ansible.builtin.apt:
#     pkg:
#       - apparmor
#       - bluez
#       - cifs-utils
#       - curl
#       - dbus
#       - jq
#       - libglib2.0-bin
#       - lsb-release
#       - network-manager
#       - nfs-common
#       - systemd-journal-remote
#       - systemd-resolved
#       - udisks2
#       - wget
