---
- name: Install preferred packages
  ansible.builtin.apt:
    pkg:
      - htop
      - iotop
      - strace

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - apparmor
      - bluez
      - cifs-utils
      - curl
      - dbus
      - jq
      - libglib2.0-bin
      - lsb-release
      - network-manager
      - nfs-common
      - systemd-journal-remote
      - systemd-resolved
      - udisks2
      - wget

- name: Install required packages for docker
  ansible.builtin.apt:
    pkg:
      - ca-certificates

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Create Docker repository file
  ansible.builtin.copy:
    content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_facts.distribution_release }} stable"
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'

- name: Install docker
  ansible.builtin.apt:
    pkg:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    update_cache: true