---
- name: End the play for non-Debian 12 hosts
  ansible.builtin.meta: end_play
  when: not (ansible_os_family == 'Debian' and ansible_distribution_major_version | int == hass_supported_osrelease)

- name: Gather package_facts to verify NetworkManager package status
  ansible.builtin.package_facts:
    manager: apt

- name: Check if system is already managed by NetworkManager
  ansible.builtin.shell: "nmcli device status | grep {{ ansible_facts.default_ipv4.interface }}"
  register: hass_nm_status
  changed_when: false
  when: "'network-manager' in ansible_facts.packages"

- name: Install and configure NetworkManager
  ansible.builtin.include_tasks: networkmanager.yml
  when: "'network-manager' not in ansible_facts.packages"
